{% set name = "tortoise-orm" %}
{% set version = "0.19.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ca574bca5191f55608f9013314b1f5d1c6ffd4165a1fcc2f60f6c902f529b3b6

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.7,<4.0
  run:
    - aiosqlite >=0.16.0,<0.18.0
    - iso8601 >=1.0.2,<2.0.0
    - pypika-tortoise >=0.1.6,<0.2.0
    - python >=3.7,<4.0
    - pytz

test:
  imports:
    - tortoise
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tortoise/tortoise-orm
  doc_url: http://tortoise-orm.readthedocs.io/en/latest/
  summary: Easy async ORM for python, built with relations in mind
  license: Apache-2.0
  license_file: LICENSE.txt
  description: |
    Tortoise ORM is an easy-to-use asyncio ORM (Object Relational Mapper)
     inspired by Django. Tortoise ORM was built with relations in mind and
     admiration for the excellent and popular Django ORM. It's engraved in its
     design that you are working not with just tables, you work with relational
     data.

extra:
  recipe-maintainers:
    - thewchan
