{% set name = "tortoise-orm" %}
{% set version = "0.25.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 7d0aaf31c33a25a9efad8f94b44ee50febae15889f4da119cf184ffe98002673

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - pypika-tortoise >=0.5.0,<0.6.0
    - iso8601 >=2.1.0,<3.0.0
    - aiosqlite >=0.16.0,<0.21.0
    - pytz

test:
  imports:
    - tortoise
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tortoise/tortoise-orm
  doc_url: http://tortoise-orm.readthedocs.io/en/latest/
  summary: Easy async ORM for python, built with relations in mind
  license: Apache-2.0
  license_file: LICENSE.txt
  description: |
    Tortoise ORM is an easy-to-use asyncio ORM (Object Relational Mapper)
     inspired by Django. Tortoise ORM was built with relations in mind and
     admiration for the excellent and popular Django ORM. It's engraved in its
     design that you are working not with just tables, you work with relational
     data.

extra:
  recipe-maintainers:
    - thewchan
