{% set name = "tortoise-orm" %}
{% set version = "0.19.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tortoise-orm-{{ version }}.tar.gz
  sha256: ad9f0c59ec2ed889c77b58857125038561cbe3846438cf20d39a7919ea62aecb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.6,<4.0
  run:
    - aiohttp >=3.7.4
    - aiosqlite >=0.16.0,<0.17.0
    - astroid >=2.5.7
    - asyncpg >=0.23.0
    - fastapi >=0.65.1
    - iso8601 >=0.1.13,<0.2.0
    - pydantic >=1.8.2
    - pylint >=2.7.2
    - pypika-tortoise >=0.1.2,<0.2.0
    - python >=3.6,<4.0
    - pytz
    - quart >=0.15.1
    - sanic >=21.3.4
    - starlette >=0.14.2
    - typing_extensions >=3.7.2

test:
  imports:
    - tortoise
    - tortoise.backends
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tortoise/tortoise-orm
  doc_url: http://tortoise-orm.readthedocs.io/en/latest/
  summary: Easy async ORM for python, built with relations in mind
  license: Apache-2.0
  license_file: LICENSE.txt
  description: |
    Tortoise ORM is an easy-to-use asyncio ORM (Object Relational Mapper)
     inspired by Django. Tortoise ORM was built with relations in mind and
     admiration for the excellent and popular Django ORM. It's engraved in its
     design that you are working not with just tables, you work with relational
     data.

extra:
  recipe-maintainers:
    - thewchan
