schema_version: 1

context:
  name: tortoise-orm
  version: 0.25.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 7d0aaf31c33a25a9efad8f94b44ee50febae15889f4da119cf184ffe98002673

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python ${{ python_min }}.*
  run:
    - python >=${{ python_min }}
    - pypika-tortoise >=0.5.0,<0.6.0
    - iso8601 >=2.1.0,<3.0.0
    - aiosqlite >=0.16.0,<0.21.0
    - pytz

tests:
  - python:
      imports:
        - tortoise
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Easy async ORM for python, built with relations in mind
  license: Apache-2.0
  license_file: LICENSE.txt
  description: |
    Tortoise ORM is an easy-to-use asyncio ORM (Object Relational Mapper)
    inspired by Django. Tortoise ORM was built with relations in mind and
    admiration for the excellent and popular Django ORM. It's engraved in its
    design that you are working not with just tables, you work with relational
    data.


  homepage: https://github.com/tortoise/tortoise-orm
  documentation: http://tortoise-orm.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - thewchan
