schema_version: 1

context:
  name: tortoise-orm
  version: "1.1.4"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 90a99adb7afe7ccbdc9c8e47709b488676ef762facba8bdca80adf6175359413

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pdm-backend
    - python ${{ python_min }}.*
  run:
    - python >=${{ python_min }}
    - pypika-tortoise >=0.6.3,<1.0.0
    - iso8601 >=2.1.0,<3.0.0
    - aiosqlite >=0.16.0,<1.0.0
    - pytz
    - anyio
    - typing-extensions >=4.1.0
    - tomlkit >=0.11.4,<1.0.0

tests:
  - python:
      imports:
        - tortoise
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Easy async ORM for python, built with relations in mind
  license: Apache-2.0
  license_file: LICENSE.txt
  description: |
    Tortoise ORM is an easy-to-use asyncio ORM (Object Relational Mapper)
    inspired by Django. Tortoise ORM was built with relations in mind and
    admiration for the excellent and popular Django ORM. It's engraved in its
    design that you are working not with just tables, you work with relational
    data.


  homepage: https://github.com/tortoise/tortoise-orm
  documentation: https://tortoise.github.io/

extra:
  recipe-maintainers:
    - thewchan
